name: Manual Test Runner

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  test:
    name: Run Tests on Selected OS
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ inputs.os == 'ubuntu-latest' && 'x86_64-unknown-linux-gnu' || inputs.os == 'macos-latest' && 'x86_64-apple-darwin' || inputs.os == 'windows-latest' && 'x86_64-pc-windows-msvc' }}

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run tests on Linux/macOS
        if: ${{ inputs.os != 'windows-latest' }}
        run: cargo nextest run --workspace --no-fail-fast --no-capture
        shell: bash

      - name: Run tests on Windows
        if: ${{ inputs.os == 'windows-latest' }}
        run: cargo nextest run --workspace --no-fail-fast --no-capture
        shell: pwsh
